### ISSUE TITLE
Able to check out with hidden prices

### ISSUE THREAD

**Issue by ajgagnon** [Freemius/pricing-page#6]
It looks like if plans have different prices, the default price is always 1 site, even if this price is hidden. Here's the pricing page:

![image](https://user-images.githubusercontent.com/2569725/93518701-ce970800-f8f2-11ea-9125-196f86ddce58.png)

When checking out, even if the 3 sites license is selected, it defaults to single site license on checkout:

![image](https://user-images.githubusercontent.com/2569725/93518776-ea021300-f8f2-11ea-964c-1f5be2d2b3a0.png)

I believe this is because:

1. selectedLicenseQuantity state is only updated on change, and not on load. 
2. selectedLicenseQuantity is a single value and not scoped to plans specifically. I think each plan component should keep track of this value, rather than a global state value. Or if stored in global state, should be an array or object to keep track of which plan has which quantity selected.

This would allow for more flexibility.

**Comment by xiahengchen** [comment]
Hi @ajgagnon, thank you for reporting! We have fixed the issue that you mentioned above and you can simply checkout [feature/redirect-to-checkout-fix](https://github.com/Freemius/pricing-page/tree/feature/redirect-to-checkout-fix) branch to check the changes.

**Comment by vovafeldman** [comment]
Closed https://github.com/Freemius/pricing-page/pull/10
